services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: Ailluminator
      POSTGRES_PASSWORD: Avatar30.11  # You can change this
    volumes:
      - ./database_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydb
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data:
