services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: Ailluminator
      POSTGRES_PASSWORD: Avatar30.11  # You can change this
    volumes:
      - ./database_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: Ailluminator
      DATABASE_PASSWORD: Avatar30.11
      DATABASE_NAME: mydb

volumes:
  db_data:
