services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: Ailluminator
      POSTGRES_PASSWORD: Avatar30.11  # You can change this
    volumes:
      - ./database_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    restart: always
    networks:
      - ailluminator

  web:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: Ailluminator
      DATABASE_PASSWORD: Avatar30.11
      DATABASE_NAME: papers
    networks:
      - ailluminator
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # HTTP
      # - "443:443"  # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use the custom Nginx config file
    depends_on:
      - web
    networks:
      - ailluminator


volumes:
  db_data:

networks:
  ailluminator:
    name: ailluminator